name: Generate Brick Breaker Animation

on:
  schedule:
    # Berjalan otomatis setiap hari pukul 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Brick Breaker SVG
        uses: MakdumIbrohim/generate-brick-breaker@main
        with:
          github_user_name: ${{ github.repository_owner }}
          output_path: dist/brick-breaker.svg

      - name: Push Output to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
